### ISSUE TITLE
Recursion across array of sentences?

### ISSUE THREAD

**Issue by Ganasist** [jstejada/react-typist#21]
Love this package!

Would love it even more if I could easily pass an array and have it type one sentence at a time (replacing each time). There is currently not a simple way to do this... I tried to use onTypingDone to call itself again but no luck:

```
const typeSentence = (sentence) => {
  return (
      <Typist
          avgTypingDelay={50}
          cursor={
          {
            show: true,
            blink: true,
            element: '|',
            hideWhenDone: false,
            hideWhenDoneDelay: 1000,
          }
          }
          onTypingDone={() => typeSentence(sample([sentenceArray])}
          startDelay={1000}
          stdTypingDelay={20}
      >
        {sentence}
      </Typist>
  );
};
```

**Comment by jstejada** [comment]
thanks for reporting this! You want to be able to replace the sentence with different sentences from an aray correct?

this should be achievable by doing something like:
```jsx
render() {
  const {sentence} = this.state
  return <Typist onTypistDone={() => {this.setState({sentence: getNextSentence()})}}>{sentence}</Typist>
}
```

or something of the sort.

However, I'm pretty sure this wont work due to #29, which I will look into soon.
For now, I'm going to merge this issue into #29. 

Thanks again!
